// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Analyzes fraud reports to identify potential abuse or false positives and recommends numbers for further investigation.
 *
 * - analyzeFraudReport - Analyzes a fraud report and returns a recommendation for further investigation.
 * - AnalyzeFraudReportInput - The input type for the analyzeFraudReport function.
 * - AnalyzeFraudReportOutput - The return type for the analyzeFraudReport function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeFraudReportInputSchema = z.object({
  reportText: z.string().describe('The text content of the fraud report.'),
  reporterPhoneNumber: z.string().describe('The phone number of the person submitting the report.'),
  reportedPhoneNumber: z.string().describe('The phone number being reported for fraud.'),
});
export type AnalyzeFraudReportInput = z.infer<typeof AnalyzeFraudReportInputSchema>;

const AnalyzeFraudReportOutputSchema = z.object({
  isSuspicious: z.boolean().describe('Whether the report is deemed suspicious and requires further investigation.'),
  reason: z.string().describe('The reason for the suspicion or lack thereof.'),
});
export type AnalyzeFraudReportOutput = z.infer<typeof AnalyzeFraudReportOutputSchema>;

export async function analyzeFraudReport(input: AnalyzeFraudReportInput): Promise<AnalyzeFraudReportOutput> {
  return analyzeFraudReportFlow(input);
}

const analyzeFraudReportPrompt = ai.definePrompt({
  name: 'analyzeFraudReportPrompt',
  input: {schema: AnalyzeFraudReportInputSchema},
  output: {schema: AnalyzeFraudReportOutputSchema},
  prompt: `You are an expert fraud analyst tasked with reviewing newly submitted fraud reports. Your goal is to identify reports that are potentially abusive, false positives, or otherwise require further investigation.

  Analyze the following fraud report and determine if it is suspicious. Consider factors such as the report's content, the reporter's phone number, and the reported phone number. Look for patterns that might indicate abuse or false positives. For example:

  - Vague or nonsensical reports
  - Reports that contradict each other
  - Reports from the same reporter about many different numbers
  - Reports that seem to be targeting a specific number or individual

  Based on your analysis, indicate whether the report is suspicious and provide a reason for your determination.

  Report Text: {{{reportText}}}
  Reporter Phone Number: {{{reporterPhoneNumber}}}
  Reported Phone Number: {{{reportedPhoneNumber}}}
  `,
});

const analyzeFraudReportFlow = ai.defineFlow(
  {
    name: 'analyzeFraudReportFlow',
    inputSchema: AnalyzeFraudReportInputSchema,
    outputSchema: AnalyzeFraudReportOutputSchema,
  },
  async input => {
    const {output} = await analyzeFraudReportPrompt(input);
    return output!;
  }
);
